//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventReg.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAdmin
    {
        public int CustomerAdminID { get; set; }
        public int AdminID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
